name: Build Binaries

on:
  push:
    branches: [ dev ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pkg
        run: npm install -g pkg

      - name: Build
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            pkg git-commit.js --targets node18-win-x64
          elif [ "$RUNNER_OS" = "Linux" ]; then
            pkg git-commit.js --targets node18-linux-x64
          elif [ "$RUNNER_OS" = "macOS" ]; then
            pkg git-commit.js --targets node18-macos-x64,node18-macos-arm64
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ runner.os }}
          path: |
            *.exe
            git-commit*
